version: '3.8'

services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/etc/nginx/html
    ports:
      - 8080:80
    depends_on:
      - 'frontend'
      - 'backend'

  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    volumes:
      - static:/usr/src/app/build
    environment:
      - REACT_APP_BACKEND_URL=/api/
      - NODE_ENV=production
    command: npm run build 

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment: 
      - PORT=3001
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://username:password@mongo:27017/database
      - NODE_ENV=production
    command: npm start

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
      
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data

volumes:
  static: