services:
  server:
    image: todo-backend-dev
    container_name: server
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    environment: 
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://username:password@mongo:27017/database
  mongo:
    image: mongo
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
  redis:
    image: redis
    container_name: cache
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data